[package]
name = "tomato_lib"
version = "0.1.0"
edition = "2021"


[lib]
name = "tomato_lib"           # The name of the target.
path = "src/mod.rs"    # The source file of the target.


[[bin]]
name = "main"
path = "main.rs"

